{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: {{ .Values.allowHttp | default "false" | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/client-max-body-size: "10m"
    acme.cert-manager.io/http01-edit-in-place: "true"
  name: {{ printf "%s-%s" .Release.Name "bookstack" }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ required "appHost is required when ingress.enabled is true" .Values.appHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: {{ printf "%s-%s" .Release.Name "bookstack" }}
              port:
                number: {{ default 8080 .Values.service.port }}
        
  tls:
  - hosts:
    - {{ .Values.appHost }}
    secretName: {{ printf "%s-%s" .Release.Name "bookstack" }}
{{- end }}
